training:
  lr: 0.01
  weight-decay: 0.000001
  bs: 32 # batch-size
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 30 # Equidistant frames
  mask-method: 'noise' # 'black', 'noise' or 'none'
  mask-number: 6 # range(0, 9)
  picture-color: 'rgb' # 'rgb' or 'gray'

model:
  image-size: 224
  SRM-net: 'no' # use SRM net or not.'yes' or 'no'